/**
 * 都道府県データ及び主要市区町村データ
 * Prefecture and major city data for Japan
 */

// Prefecture data with codes
const prefectures = [
    {code: "01", name: "北海道"},
    {code: "02", name: "青森県"},
    {code: "03", name: "岩手県"},
    {code: "04", name: "宮城県"},
    {code: "05", name: "秋田県"},
    {code: "06", name: "山形県"},
    {code: "07", name: "福島県"},
    {code: "08", name: "茨城県"},
    {code: "09", name: "栃木県"},
    {code: "10", name: "群馬県"},
    {code: "11", name: "埼玉県"},
    {code: "12", name: "千葉県"},
    {code: "13", name: "東京都"},
    {code: "14", name: "神奈川県"},
    {code: "15", name: "新潟県"},
    {code: "16", name: "富山県"},
    {code: "17", name: "石川県"},
    {code: "18", name: "福井県"},
    {code: "19", name: "山梨県"},
    {code: "20", name: "長野県"},
    {code: "21", name: "岐阜県"},
    {code: "22", name: "静岡県"},
    {code: "23", name: "愛知県"},
    {code: "24", name: "三重県"},
    {code: "25", name: "滋賀県"},
    {code: "26", name: "京都府"},
    {code: "27", name: "大阪府"},
    {code: "28", name: "兵庫県"},
    {code: "29", name: "奈良県"},
    {code: "30", name: "和歌山県"},
    {code: "31", name: "鳥取県"},
    {code: "32", name: "島根県"},
    {code: "33", name: "岡山県"},
    {code: "34", name: "広島県"},
    {code: "35", name: "山口県"},
    {code: "36", name: "徳島県"},
    {code: "37", name: "香川県"},
    {code: "38", name: "愛媛県"},
    {code: "39", name: "高知県"},
    {code: "40", name: "福岡県"},
    {code: "41", name: "佐賀県"},
    {code: "42", name: "長崎県"},
    {code: "43", name: "熊本県"},
    {code: "44", name: "大分県"},
    {code: "45", name: "宮崎県"},
    {code: "46", name: "鹿児島県"},
    {code: "47", name: "沖縄県"}
  ];
  
  // Major cities for each prefecture
  const majorCities = {
    "01": [{name: "札幌市"}, {name: "函館市"}, {name: "旭川市"}, {name: "釧路市"}],
    "02": [{name: "青森市"}, {name: "弘前市"}, {name: "八戸市"}],
    "03": [{name: "盛岡市"}, {name: "一関市"}, {name: "宮古市"}],
    "04": [{name: "仙台市"}, {name: "石巻市"}, {name: "大崎市"}],
    "05": [{name: "秋田市"}, {name: "横手市"}, {name: "大仙市"}],
    "06": [{name: "山形市"}, {name: "酒田市"}, {name: "鶴岡市"}],
    "07": [{name: "福島市"}, {name: "郡山市"}, {name: "いわき市"}],
    "08": [{name: "水戸市"}, {name: "つくば市"}, {name: "日立市"}],
    "09": [{name: "宇都宮市"}, {name: "小山市"}, {name: "栃木市"}],
    "10": [{name: "前橋市"}, {name: "高崎市"}, {name: "太田市"}],
    "11": [{name: "さいたま市"}, {name: "川越市"}, {name: "所沢市"}],
    "12": [{name: "千葉市"}, {name: "船橋市"}, {name: "柏市"}],
    "13": [{name: "新宿区"}, {name: "渋谷区"}, {name: "八王子市"}, {name: "町田市"}],
    "14": [{name: "横浜市"}, {name: "川崎市"}, {name: "相模原市"}],
    "15": [{name: "新潟市"}, {name: "長岡市"}, {name: "上越市"}],
    "16": [{name: "富山市"}, {name: "高岡市"}, {name: "射水市"}],
    "17": [{name: "金沢市"}, {name: "七尾市"}, {name: "小松市"}],
    "18": [{name: "福井市"}, {name: "敦賀市"}, {name: "越前市"}],
    "19": [{name: "甲府市"}, {name: "富士吉田市"}, {name: "甲州市"}],
    "20": [{name: "長野市"}, {name: "松本市"}, {name: "上田市"}],
    "21": [{name: "岐阜市"}, {name: "大垣市"}, {name: "高山市"}],
    "22": [{name: "静岡市"}, {name: "浜松市"}, {name: "沼津市"}],
    "23": [{name: "名古屋市"}, {name: "豊田市"}, {name: "岡崎市"}],
    "24": [{name: "津市"}, {name: "四日市市"}, {name: "松阪市"}],
    "25": [{name: "大津市"}, {name: "彦根市"}, {name: "長浜市"}],
    "26": [{name: "京都市"}, {name: "宇治市"}, {name: "舞鶴市"}],
    "27": [{name: "大阪市"}, {name: "堺市"}, {name: "東大阪市"}],
    "28": [{name: "神戸市"}, {name: "姫路市"}, {name: "西宮市"}],
    "29": [{name: "奈良市"}, {name: "橿原市"}, {name: "生駒市"}],
    "30": [{name: "和歌山市"}, {name: "田辺市"}, {name: "新宮市"}],
    "31": [{name: "鳥取市"}, {name: "米子市"}, {name: "倉吉市"}],
    "32": [{name: "松江市"}, {name: "出雲市"}, {name: "浜田市"}],
    "33": [{name: "岡山市"}, {name: "倉敷市"}, {name: "津山市"}],
    "34": [{name: "広島市"}, {name: "福山市"}, {name: "呉市"}],
    "35": [{name: "山口市"}, {name: "下関市"}, {name: "宇部市"}],
    "36": [{name: "徳島市"}, {name: "鳴門市"}, {name: "阿南市"}],
    "37": [{name: "高松市"}, {name: "丸亀市"}, {name: "観音寺市"}],
    "38": [{name: "松山市"}, {name: "今治市"}, {name: "新居浜市"}],
    "39": [{name: "高知市"}, {name: "南国市"}, {name: "土佐市"}],
    "40": [{name: "福岡市"}, {name: "北九州市"}, {name: "久留米市"}],
    "41": [{name: "佐賀市"}, {name: "唐津市"}, {name: "鳥栖市"}],
    "42": [{name: "長崎市"}, {name: "佐世保市"}, {name: "諫早市"}],
    "43": [{name: "熊本市"}, {name: "八代市"}, {name: "天草市"}],
    "44": [{name: "大分市"}, {name: "別府市"}, {name: "中津市"}],
    "45": [{name: "宮崎市"}, {name: "都城市"}, {name: "延岡市"}],
    "46": [{name: "鹿児島市"}, {name: "霧島市"}, {name: "鹿屋市"}],
    "47": [{name: "那覇市"}, {name: "沖縄市"}, {name: "宮古島市"}]